# This is a basic workflow to help you get started with Actions

name: Coverage

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Define python version.
    env:
      PYTHON: '3.8'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository to main branch
      - uses: actions/checkout@main
      
      # Set up python environment.
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
          
      # Install coverage dependencies and generate report.
      - name: Generate coverage report
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml

      # Using the generated report, upload to codecov.
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage1.xml,./coverage2.xml
          directory: ./coverage/reports/
          flags: unittests
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
